#______commByCritByGroup_________#
commByCritByGroup = {'A2': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'conclusion numerical checked by analytical': 'really_confusing', 'results numerical': '', 'introduction': '', '1deg sys': '', 'discussion limits': '', 'penalization units': '', 'discussion type': '', 'description numerical': '', 'description analytical numerial relation': '', 'penalization grammar': ''},
 'A11': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'conclusion numerical checked by analytical': '', 'results numerical': '', 'introduction': '', '1deg sys': '', 'discussion limits': '', 'penalization units': '', 'discussion type': '', 'description numerical': '', 'description analytical numerial relation': '', 'penalization grammar': ''},
 'A12': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'conclusion numerical checked by analytical': '', 'results numerical': '', 'introduction': '', '1deg sys': '', 'discussion limits': '', 'penalization units': '', 'discussion type': '', 'description numerical': '', 'description analytical numerial relation': '', 'penalization grammar': ''},
 'A1': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'conclusion numerical checked by analytical': '', 'results numerical': '', 'introduction': '', '1deg sys': '', 'discussion limits': '', 'penalization units': '', 'discussion type': '', 'description numerical': '', 'description analytical numerial relation': '', 'penalization grammar': ''},
 'A3': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'description numerical': '', 'penalization units': '', 'discussion limits': '', 'introduction': '', '1deg sys': '', 'results numerical': 'no_time_evolution', 'penalization grammar': '', 'discussion type': '', 'conclusion numerical checked by analytical': '', 'description analytical numerial relation': ''},
 'C8': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'conclusion numerical checked by analytical': '', 'results numerical': '', 'introduction': '', '1deg sys': '', 'discussion limits': 'units_wron', 'penalization grammar': '', 'discussion type': '', 'description numerical': '', 'description analytical numerial relation': '', 'penalization units': ''},
 'A5': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'conclusion numerical checked by analytical': '', 'results numerical': '', 'introduction': '', '1deg sys': '', 'discussion limits': '', 'penalization grammar': '', 'discussion type': '', 'description numerical': '', 'description analytical numerial relation': '', 'penalization units': ''},
 'A4': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'description numerical': '', 'penalization units': '', 'discussion limits': '', 'introduction': '', '1deg sys': '', 'results numerical': '', 'penalization grammar': '', 'discussion type': '', 'conclusion numerical checked by analytical': '', 'description analytical numerial relation': ''},
 'A7': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'description numerical': '', 'penalization grammar': '', 'discussion limits': '', 'introduction': '', '1deg sys': '', 'results numerical': '', 'penalization units': '', 'discussion type': '', 'conclusion numerical checked by analytical': '', 'description analytical numerial relation': ''},
 'A6': {'discussion singularity': 'mention_to_singular_movement', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'description numerical': '', 'penalization grammar': '', 'discussion limits': '', 'introduction': '', '1deg sys': '', 'results numerical': '', 'penalization units': '', 'discussion type': '', 'conclusion numerical checked by analytical': '', 'description analytical numerial relation': ''},
 'C3': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'conclusion numerical checked by analytical': '', 'results numerical': '', 'introduction': '', '1deg sys': '', 'discussion limits': '', 'penalization grammar': '', 'discussion type': '', 'description numerical': '', 'description analytical numerial relation': '', 'penalization units': ''},
 'C2': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'conclusion numerical checked by analytical': '', 'results numerical': '', 'introduction': '', '1deg sys': '', 'discussion limits': '', 'penalization grammar': '', 'discussion type': '', 'description numerical': '', 'description analytical numerial relation': '', 'penalization units': ''},
 'C1': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'description numerical': '', 'penalization grammar': '', 'discussion limits': '', 'introduction': '', '1deg sys': '', 'results numerical': '', 'penalization units': '', 'discussion type': '', 'conclusion numerical checked by analytical': '', 'description analytical numerial relation': ''},
 'C7': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'description numerical': '', 'penalization units': '', 'discussion limits': '', 'introduction': '', '1deg sys': '', 'results numerical': '', 'penalization grammar': '', 'discussion type': 'this_is_zero,_the_limits_are_right', 'conclusion numerical checked by analytical': '', 'description analytical numerial relation': ''},
 'C6': {'discussion singularity': '', 'extra point for work': '', 'description analytical': 'implementation_detials', 'results analytical': '', 'conclusion numerical checked by analytical': '', 'results numerical': '', 'introduction': '', '1deg sys': '', 'discussion limits': '', 'penalization units': '', 'discussion type': '', 'description numerical': 'implementation_details', 'description analytical numerial relation': '', 'penalization grammar': ''},
 'C4': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'description numerical': '', 'penalization grammar': '', 'discussion limits': '', 'introduction': '', '1deg sys': '', 'results numerical': '', 'penalization units': '', 'discussion type': '', 'conclusion numerical checked by analytical': 'does_not_say_it_explicitely_in_conclusions,_but_in_the_whole_report', 'description analytical numerial relation': ''},
 'A8': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'description numerical': '', 'penalization grammar': '', 'discussion limits': 'units_wron', 'introduction': '', '1deg sys': '', 'results numerical': '', 'penalization units': '', 'discussion type': '', 'conclusion numerical checked by analytical': '', 'description analytical numerial relation': ''},
 'B8': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'description numerical': '', 'penalization units': '', 'discussion limits': '', 'introduction': '', '1deg sys': '', 'results numerical': '', 'penalization grammar': '', 'discussion type': '', 'conclusion numerical checked by analytical': 'mention_to_the_use_of_both_methods', 'description analytical numerial relation': ''},
 'B4': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'conclusion numerical checked by analytical': '', 'results numerical': '', 'introduction': '', '1deg sys': '', 'discussion limits': '', 'penalization grammar': '', 'discussion type': '', 'description numerical': '', 'description analytical numerial relation': '', 'penalization units': ''},
 'B5': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'description numerical': '', 'penalization grammar': '', 'discussion limits': '', 'introduction': '', '1deg sys': '', 'results numerical': '', 'penalization units': '', 'discussion type': '', 'conclusion numerical checked by analytical': '', 'description analytical numerial relation': ''},
 'B6': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'conclusion numerical checked by analytical': '', 'results numerical': '', 'introduction': '', '1deg sys': '', 'discussion limits': '', 'penalization units': '', 'discussion type': '', 'description numerical': '', 'description analytical numerial relation': '', 'penalization grammar': ''},
 'B1': {'discussion singularity': 'does_not_clarify_what_is_small_value', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'description numerical': '', 'penalization units': '', 'discussion limits': '', 'introduction': '', '1deg sys': '', 'results numerical': '', 'penalization grammar': '', 'discussion type': '', 'conclusion numerical checked by analytical': 'mention_to_the_more_reliability_of_analytical_solutions', 'description analytical numerial relation': ''},
 'B2': {'discussion singularity': '', 'extra point for work': '', 'description analytical': 'wrong', 'results analytical': '', 'description numerical': 'totally_wrong', 'penalization units': '', 'discussion limits': 'poor_description', 'introduction': '', '1deg sys': '', 'results numerical': '', 'penalization grammar': '', 'discussion type': 'poor_description', 'conclusion numerical checked by analytical': '', 'description analytical numerial relation': ''},
 'D6': {'discussion limits': '', 'introduction': '', 'description analytical': '', 'discussion singularity': '', '1deg sys': '', 'results numerical': '', 'results analytical': '', 'penalization grammar': '', 'discussion type': '', 'extra point for work': '', 'description numerical': '', 'penalization units': '', 'conclusion numerical checked by analytical': '', 'description analytical numerial relation': ''},
 'D4': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'conclusion numerical checked by analytical': '', 'results numerical': '', 'introduction': '', '1deg sys': '', 'discussion limits': '', 'penalization grammar': '', 'discussion type': '', 'description numerical': '', 'description analytical numerial relation': '', 'penalization units': ''},
 'D5': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'description numerical': '', 'penalization units': '', 'discussion limits': '', 'introduction': '', '1deg sys': '', 'results numerical': '', 'penalization grammar': '', 'discussion type': '', 'conclusion numerical checked by analytical': '', 'description analytical numerial relation': ''},
 'D2': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'conclusion numerical checked by analytical': '', 'results numerical': '', 'introduction': '', '1deg sys': '', 'discussion limits': '', 'penalization units': '', 'discussion type': '', 'description numerical': '', 'description analytical numerial relation': '', 'penalization grammar': ''},
 'D3': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'description numerical': '', 'penalization units': '', 'discussion limits': '', 'introduction': '', '1deg sys': '', 'results numerical': '', 'penalization grammar': '', 'discussion type': '', 'conclusion numerical checked by analytical': '', 'description analytical numerial relation': ''},
 'D1': {'discussion singularity': '', 'extra point for work': '', 'description analytical': '', 'results analytical': '', 'description numerical': '', 'penalization grammar': '', 'discussion limits': '', 'introduction': '', '1deg sys': '', 'results numerical': '', 'penalization units': '', 'discussion type': '', 'conclusion numerical checked by analytical': '', 'description analytical numerial relation': ''}}
#______valByCritByGroup_________#
valByCritByGroup = {'A2': {'discussion singularity': 1.0, 'extra point for work': 0.0, 'description analytical': 1.0, 'results analytical': 1.0, 'conclusion numerical checked by analytical': 0.2, 'results numerical': 1.0, 'introduction': 1.0, '1deg sys': 0.0, 'discussion limits': 1.0, 'penalization units': 0.0, 'discussion type': 0.0, 'description numerical': 1.0, 'description analytical numerial relation': 1.0, 'penalization grammar': 0.0},       
 'A11': {'discussion singularity': 0.0, 'extra point for work': 1.0, 'description analytical': 0.0, 'results analytical': 1.0, 'conclusion numerical checked by analytical': 1.0, 'results numerical': 1.0, 'introduction': 1.0, '1deg sys': 0.0, 'discussion limits': 1.0, 'penalization units': -1.0, 'discussion type': 0.0, 'description numerical': 0.0, 'description analytical numerial relation': 0.0, 'penalization grammar': 0.0},       
 'A12': {'discussion singularity': 0.2, 'extra point for work': 0.0, 'description analytical': 1.0, 'results analytical': 1.0, 'conclusion numerical checked by analytical': 0.0, 'results numerical': 0.7, 'introduction': 1.0, '1deg sys': 1.0, 'discussion limits': 0.0, 'penalization units': 1.0, 'discussion type': 0.0, 'description numerical': 1.0, 'description analytical numerial relation': 0.0, 'penalization grammar': 0.0},       
 'A1': {'discussion singularity': 0.0, 'extra point for work': 0.0, 'description analytical': 1.0, 'results analytical': 0.0, 'conclusion numerical checked by analytical': 1.0, 'results numerical': 0.0, 'introduction': 1.0, '1deg sys': 0.0, 'discussion limits': 0.0, 'penalization units': 0.0, 'discussion type': 0.0, 'description numerical': 1.0, 'description analytical numerial relation': 1.0, 'penalization grammar': 0.0},       
 'A3': {'discussion singularity': 1.0, 'extra point for work': 1.0, 'description analytical': 1.0, 'results analytical': 0.0, 'description numerical': 1.0, 'penalization units': 0.0, 'discussion limits': 1.0, 'introduction': 1.0, '1deg sys': 0.0, 'results numerical': 0.7, 'penalization grammar': 0.0, 'discussion type': 1.0, 'conclusion numerical checked by analytical': 1.0, 'description analytical numerial relation': 0.0},       
 'C8': {'discussion singularity': 1.0, 'extra point for work': 0.0, 'description analytical': 1.0, 'results analytical': 1.0, 'conclusion numerical checked by analytical': 1.0, 'results numerical': 1.0, 'introduction': 1.0, '1deg sys': 0.0, 'discussion limits': 0.8, 'penalization grammar': 0.0, 'discussion type': 0.0, 'description numerical': 1.0, 'description analytical numerial relation': 0.0, 'penalization units': 0.0},       
 'A5': {'discussion singularity': 0.0, 'extra point for work': 1.0, 'description analytical': 1.0, 'results analytical': 1.0, 'conclusion numerical checked by analytical': 0.2, 'results numerical': 0.7, 'introduction': 1.0, '1deg sys': 0.0, 'discussion limits': 0.0, 'penalization grammar': 0.0, 'discussion type': 1.0, 'description numerical': 1.0, 'description analytical numerial relation': 1.0, 'penalization units': 0.0},       
 'A4': {'discussion singularity': 0.0, 'extra point for work': 1.0, 'description analytical': 1.0, 'results analytical': 1.0, 'description numerical': 1.0, 'penalization units': 0.0, 'discussion limits': 1.0, 'introduction': 1.0, '1deg sys': 0.0, 'results numerical': 0.7, 'penalization grammar': 0.0, 'discussion type': 1.0, 'conclusion numerical checked by analytical': 1.0, 'description analytical numerial relation': 1.0},       
 'A7': {'discussion singularity': 1.0, 'extra point for work': 0.0, 'description analytical': 1.0, 'results analytical': 1.0, 'description numerical': 1.0, 'penalization grammar': 0.0, 'discussion limits': 1.0, 'introduction': 1.0, '1deg sys': 0.0, 'results numerical': 0.7, 'penalization units': 0.0, 'discussion type': 1.0, 'conclusion numerical checked by analytical': 0.0, 'description analytical numerial relation': 0.0},       
 'A6': {'discussion singularity': 0.2, 'extra point for work': 1.0, 'description analytical': 1.0, 'results analytical': 1.0, 'description numerical': 1.0, 'penalization grammar': 0.0, 'discussion limits': 1.0, 'introduction': 1.0, '1deg sys': 1.0, 'results numerical': 1.0, 'penalization units': 0.0, 'discussion type': 1.0, 'conclusion numerical checked by analytical': 1.0, 'description analytical numerial relation': 1.0},       
 'C3': {'discussion singularity': 0.0, 'extra point for work': 0.0, 'description analytical': 0.0, 'results analytical': 0.0, 'conclusion numerical checked by analytical': 0.0, 'results numerical': 0.0, 'introduction': 0.0, '1deg sys': 0.0, 'discussion limits': 0.0, 'penalization grammar': 0.0, 'discussion type': 0.0, 'description numerical': 0.0, 'description analytical numerial relation': 0.0, 'penalization units': 0.0},       
 'C2': {'discussion singularity': 0.0, 'extra point for work': 0.0, 'description analytical': 0.0, 'results analytical': 0.0, 'conclusion numerical checked by analytical': 0.0, 'results numerical': 0.0, 'introduction': 0.0, '1deg sys': 0.0, 'discussion limits': 0.0, 'penalization grammar': 0.0, 'discussion type': 0.0, 'description numerical': 0.0, 'description analytical numerial relation': 0.0, 'penalization units': 0.0},       
 'C1': {'discussion singularity': 0.2, 'extra point for work': 1.0, 'description analytical': 1.0, 'results analytical': 1.0, 'description numerical': 1.0, 'penalization grammar': 0.0, 'discussion limits': 1.0, 'introduction': 1.0, '1deg sys': 1.0, 'results numerical': 1.0, 'penalization units': 0.0, 'discussion type': 1.0, 'conclusion numerical checked by analytical': 1.0, 'description analytical numerial relation': 1.0},       
 'C7': {'discussion singularity': 0.0, 'extra point for work': 1.0, 'description analytical': 1.0, 'results analytical': 1.0, 'description numerical': 1.0, 'penalization units': 0.0, 'discussion limits': 0.0, 'introduction': 1.0, '1deg sys': 0.0, 'results numerical': 0.7, 'penalization grammar': 0.0, 'discussion type': 1.0, 'conclusion numerical checked by analytical': 1.0, 'description analytical numerial relation': 1.0},       
 'C6': {'discussion singularity': 0.0, 'extra point for work': 1.0, 'description analytical': 0.5, 'results analytical': 1.0, 'conclusion numerical checked by analytical': 0.5, 'results numerical': 0.7, 'introduction': 1.0, '1deg sys': 0.0, 'discussion limits': 1.0, 'penalization units': 0.0, 'discussion type': 1.0, 'description numerical': 0.5, 'description analytical numerial relation': 0.0, 'penalization grammar': 0.0},       
 'C4': {'discussion singularity': 1.0, 'extra point for work': 1.0, 'description analytical': 1.0, 'results analytical': 1.0, 'description numerical': 1.0, 'penalization grammar': 0.0, 'discussion limits': 1.0, 'introduction': 1.0, '1deg sys': 0.0, 'results numerical': 1.0, 'penalization units': 0.0, 'discussion type': 1.0, 'conclusion numerical checked by analytical': 0.8, 'description analytical numerial relation': 1.0},       
 'A8': {'discussion singularity': 0.0, 'extra point for work': 1.0, 'description analytical': 1.0, 'results analytical': 1.0, 'description numerical': 1.0, 'penalization grammar': 0.0, 'discussion limits': 0.8, 'introduction': 1.0, '1deg sys': 0.0, 'results numerical': 0.7, 'penalization units': 0.0, 'discussion type': 1.0, 'conclusion numerical checked by analytical': 0.0, 'description analytical numerial relation': 0.0},       
 'B8': {'discussion singularity': 0.0, 'extra point for work': 0.0, 'description analytical': 0.0, 'results analytical': 1.0, 'description numerical': 0.0, 'penalization units': 0.0, 'discussion limits': 0.0, 'introduction': 1.0, '1deg sys': 0.0, 'results numerical': 0.0, 'penalization grammar': 0.0, 'discussion type': 0.0, 'conclusion numerical checked by analytical': 0.5, 'description analytical numerial relation': 0.0},       
 'B4': {'discussion singularity': 1.0, 'extra point for work': 1.0, 'description analytical': 1.0, 'results analytical': 1.0, 'conclusion numerical checked by analytical': 0.0, 'results numerical': 0.7, 'introduction': 1.0, '1deg sys': 0.0, 'discussion limits': 1.0, 'penalization grammar': 0.0, 'discussion type': 1.0, 'description numerical': 1.0, 'description analytical numerial relation': 0.0, 'penalization units': 0.0},       
 'B5': {'discussion singularity': 0.8, 'extra point for work': 1.0, 'description analytical': 0.0, 'results analytical': 1.0, 'description numerical': 0.0, 'penalization grammar': 0.0, 'discussion limits': 1.0, 'introduction': 1.0, '1deg sys': 0.0, 'results numerical': 1.0, 'penalization units': 0.0, 'discussion type': 1.0, 'conclusion numerical checked by analytical': 1.0, 'description analytical numerial relation': 1.0},       
 'B6': {'discussion singularity': 1.0, 'extra point for work': 1.0, 'description analytical': 1.0, 'results analytical': 1.0, 'conclusion numerical checked by analytical': 1.0, 'results numerical': 0.7, 'introduction': 1.0, '1deg sys': 0.0, 'discussion limits': 1.0, 'penalization units': 0.0, 'discussion type': 1.0, 'description numerical': 1.0, 'description analytical numerial relation': 1.0, 'penalization grammar': 0.0},       
 'B1': {'discussion singularity': 0.8, 'extra point for work': 1.0, 'description analytical': 1.0, 'results analytical': 1.0, 'description numerical': 1.0, 'penalization units': 1.0, 'discussion limits': 1.0, 'introduction': 1.0, '1deg sys': 0.0, 'results numerical': 0.7, 'penalization grammar': 0.0, 'discussion type': 0.0, 'conclusion numerical checked by analytical': 0.75, 'description analytical numerial relation': 1.0},       
 'B2': {'discussion singularity': 0.0, 'extra point for work': 0.0, 'description analytical': 0.0, 'results analytical': 1.0, 'description numerical': 0.0, 'penalization units': 1.0, 'discussion limits': 0.8, 'introduction': 1.0, '1deg sys': 0.0, 'results numerical': 1.0, 'penalization grammar': 0.0, 'discussion type': 0.8, 'conclusion numerical checked by analytical': 1.0, 'description analytical numerial relation': 1.0},       
 'D6': {'discussion limits': 0.0, 'introduction': 1.0, 'description analytical': 1.0, 'discussion singularity': 0.0, '1deg sys': 0.0, 'results numerical': 0.7, 'results analytical': 1.0, 'penalization grammar': 0.0, 'discussion type': 0.0, 'extra point for work': 0.0, 'description numerical': 1.0, 'penalization units': 0.0, 'conclusion numerical checked by analytical': 0.5, 'description analytical numerial relation': 1.0},       
 'D4': {'discussion singularity': 0.0, 'extra point for work': 0.0, 'description analytical': 0.0, 'results analytical': 1.0, 'conclusion numerical checked by analytical': 0.0, 'results numerical': 0.7, 'introduction': 1.0, '1deg sys': 0.0, 'discussion limits': 1.0, 'penalization grammar': 0.0, 'discussion type': 0.0, 'description numerical': 0.0, 'description analytical numerial relation': 0.0, 'penalization units': 0.0},       
 'D5': {'discussion singularity': 1.0, 'extra point for work': 0.0, 'description analytical': 1.0, 'results analytical': 1.0, 'description numerical': 1.0, 'penalization units': 0.0, 'discussion limits': 1.0, 'introduction': 1.0, '1deg sys': 0.0, 'results numerical': 1.0, 'penalization grammar': 0.0, 'discussion type': 0.0, 'conclusion numerical checked by analytical': 1.0, 'description analytical numerial relation': 1.0},       
 'D2': {'discussion singularity': 0.0, 'extra point for work': 1.0, 'description analytical': 1.0, 'results analytical': 1.0, 'conclusion numerical checked by analytical': 1.0, 'results numerical': 0.7, 'introduction': 1.0, '1deg sys': 0.0, 'discussion limits': 0.0, 'penalization units': 0.0, 'discussion type': 0.0, 'description numerical': 1.0, 'description analytical numerial relation': 1.0, 'penalization grammar': 0.0},       
 'D3': {'discussion singularity': 0.0, 'extra point for work': 0.0, 'description analytical': 0.0, 'results analytical': 0.0, 'description numerical': 0.0, 'penalization units': 0.0, 'discussion limits': 0.0, 'introduction': 0.0, '1deg sys': 0.0, 'results numerical': 0.0, 'penalization grammar': 0.0, 'discussion type': 0.0, 'conclusion numerical checked by analytical': 0.0, 'description analytical numerial relation': 0.0},       
 'D1': {'discussion singularity': 0.0, 'extra point for work': 0.0, 'description analytical': 1.0, 'results analytical': 1.0, 'description numerical': 1.0, 'penalization grammar': 0.0, 'discussion limits': 0.0, 'introduction': 1.0, '1deg sys': 0.0, 'results numerical': 0.7, 'penalization units': 0.0, 'discussion type': 0.0, 'conclusion numerical checked by analytical': 0.0, 'description analytical numerial relation': 1.0}}
#______commByCrit________________#
commByCrit = {'discussion singularity': ['mention_to_singular_movement', 'does_not_clarify_what_is_small_value']
, 'extra point for work': []
, 'description analytical': ['wrong', 'implementation_detials']
, 'results analytical': ['although_not_clear_roots_location']
, 'conclusion numerical checked by analytical': ['really_confusing', 'mention_to_the_more_reliability_of_analytical_solutions', 'mention_to_the_use_of_both_methods', 'does_not_say_it_explicitely_in_conclusions,_but_in_the_whole_report']
, 'results numerical': ['no_time_evolution']
, 'introduction': []
, '1deg sys': []
, 'discussion limits': ['poor_description', 'units_wron']
, 'penalization units': []
, 'discussion type': ['poor_description', 'this_is_zero,_the_limits_are_right']
, 'description numerical': ['totally_wrong', 'implementation_details']
, 'description analytical numerial relation': []
, 'penalization grammar': []
}
#______valByCrit________________#
valByCrit = {'discussion singularity': [0.2, 0.8]
, 'extra point for work': []
, 'description analytical': [0.0, 0.5]
, 'results analytical': [1.0]
, 'conclusion numerical checked by analytical': [0.2, 0.75, 0.5, 0.8]
, 'results numerical': [0.7]
, 'introduction': []
, '1deg sys': []
, 'discussion limits': [0.8, 0.8]
, 'penalization units': []
, 'discussion type': [0.8, 1.0]
, 'description numerical': [0.0, 0.5]
, 'description analytical numerial relation': []
, 'penalization grammar': []
}
