classdef File < dynamicprops
%
% \brief Class to handle output files generated by the code IBcode
%
% \author M.Moriche
%
% \date 16-05-2014 by M.Moriche \n
%       Created from NumberedFile.m
%
% \details
%
% Output files of the IBcode are contain information
%  in HDF5 format.
%
% The structure of the file is:
%
%    basename.ifr.extension for the numbered files
%
%  TUCAN generates the following structure of directory/files
%
%  path
%   |-basenm
%       |-basenm.00001.h5frame   <--- THIS IS A NUMBERED FILE
%       |-basenm.00001.h5raw     <--- THIS IS A NUMBERED FILE
%       |-basenm.sta             <--- THIS IS NOT A NUMBERED FILE
%       |-basenm.war             <--- THIS IS NOT A NUMBERED FILE
%       |-basenm.err             <--- THIS IS NOT A NUMBERED FILE
%
%  MANDATORY ARGUMENTS:
%  - path: directory where the analysis is saved
%  - basenm: reference name of the file
%  - ext: extension of the file
%  - ifrpos: position of the index in the elements
%
%  OPTIONAL ARGUMENTS:
%  - ifr=[]: index of the file (if it has). It can be initialized
%            without ifr.
%
%  PROPERTIES:
%  - path
%  - basenm
%  - ifr
% 
%  PROPERTIES PROTECTED
%   elements
%   joiner
%   regexByElement
%   ifrpos
%   ext
%   regex
%   regex_ifr
%   frmt
%
%  METHODS:
%  - getfilformat()
%  - getfilename()
%  - getfullfilename()
%
%  EXAMPLES:
%  @code
%  f = File('/home/mmoriche/data/IBcode/urv','urv_1',2,'h5frame')
%  f = File('/home/mmoriche/data/IBcode/urv','urv_1',2,'h5frame','ifr',10)
%
%  fnm = f.getfilename();
%  @endcode
%
%

properties
   path
   basenm
end 
% end properties

properties(Access='protected')
   elements = {'basenm','ext'};
   joiner = '.'
   regexByElement = struct( ...
                    'basenm' , '(\w*?)',...
                    'ifr'    , '(\d+?)',...
                    'ext'    , '(\w*?)',...
                    'joiner' ,  '\.')
   ext
   regex
   frmt
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
methods


function self = File(path,basenm,ext)
   %
   %  MANDATORY ARGUMENTS:
   %  - basenm: reference name of the analysis
   %  - ext: Extension of the file
   %
   %  OPTIONAL ARGUMENTS:
   %  - path = '.': directory where the simulation is saving the files
   %  - joiner='.': join string between elements of the filename


   n = length(self.elements) - 1;
   self.regex = '';
   for i = 1:n
      self.regex = [self.regex self.regexByElement.(self.elements{i})];
      self.regex = [self.regex self.regexByElement.joiner];
   end
   self.regex     = [self.regex self.regexByElement.(self.elements{end})];


   self.path = path;
   self.basenm = basenm;
   self.ext = ext;

   self.getfileformat();

return
end

function getfileformat(self)

   narray = misc.getformatlength(self.regex,'path',fullfile(self.path,self.basenm));
   self.frmt=['%s' self.joiner '%s'];

return
end

function fnm = getfilename(self)
  
   fnmels = {};
   for i = 1:length(self.elements)
      el = self.(self.elements{i});
      fnmels = [fnmels el];
   end
   fnm = sprintf(self.frmt, fnmels{:});
   
return
end

function fnm = getfullfilename(self)
  
   fnmels = {};
   for i = 1:length(self.elements)
      el = self.(self.elements{i});
      fnmels = [fnmels el];
   end
   fnm = sprintf(self.frmt, fnmels{:});
   fnm = fullfile(self.path, self.basenm, fnm);
return
end

end  % end methods
end  % end classdef
