function Ga = getpotential(sa,sb,Rot,xc,xx)


[A B C F G H P Q R D] = ellip.getcoeff(sa,sb,Rot,xc);

Ga = A*xx(1)^2 ...
   + B*xx(2)^2 ...
   + C*xx(3)^2 ...
   + 2*F*xx(2)*xx(3) ...
   + 2*G*xx(3)*xx(1) ...
   + 2*H*xx(1)*xx(2) ...
   + 2*P*xx(1) ...
   + 2*Q*xx(2) ...
   + 2*R*xx(3) ...
   + D;

return
end
